# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 13:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AbstractCategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images', verbose_name='Featured Image')),
                ('post_date', models.DateField(default=datetime.datetime(2019, 2, 8, 13, 28, 1, 508913, tzinfo=utc), verbose_name='Post Date')),
                ('excerpt', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-post_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.AbstractCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('blogs.abstractcategory',),
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('abstractcategorymapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.AbstractCategoryMapping')),
            ],
            options={
                'abstract': False,
            },
            bases=('blogs.abstractcategorymapping',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.AbstractPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('blogs.abstractpost',),
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractcategorymapping',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.AbstractPost'),
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='categories',
            field=models.ManyToManyField(through='blogs.CategoryMapping', to='blogs.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='abstractcategorymapping',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractcategorymapping',
            unique_together=set([('post', 'category')]),
        ),
    ]
