# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 8, 13, 41, 53, 109352, tzinfo=utc), verbose_name='Post Date'),
        ),
    ]
