# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190208_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 8, 14, 5, 58, 168425, tzinfo=utc), verbose_name='Post Date'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractcategorymapping',
            unique_together=set([]),
        ),
    ]
